version: "3.7"

services:

  client:
    build: ./client
    restart: always
    volumes:
      - ./client:/client
      - ./client/output:/client/output
    ports:
      - 5500:5500
    env_file:
      - .docker.env
      
