"""
This type stub file was generated by pyright.
"""

class BinanceAPIException(Exception):
    def __init__(self, response) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class BinanceRequestException(Exception):
    def __init__(self, message) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class BinanceOrderException(Exception):
    def __init__(self, code, message) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class BinanceOrderMinAmountException(BinanceOrderException):
    def __init__(self, value) -> None:
        ...
    


class BinanceOrderMinPriceException(BinanceOrderException):
    def __init__(self, value) -> None:
        ...
    


class BinanceOrderMinTotalException(BinanceOrderException):
    def __init__(self, value) -> None:
        ...
    


class BinanceOrderUnknownSymbolException(BinanceOrderException):
    def __init__(self, value) -> None:
        ...
    


class BinanceOrderInactiveSymbolException(BinanceOrderException):
    def __init__(self, value) -> None:
        ...
    


class BinanceWithdrawException(Exception):
    def __init__(self, message) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


